### ISSUE TITLE
statestack depends on deprecated ErrorT

### ISSUE THREAD

**Issue by bergey** [diagrams/statestack#1]
`transformers-0.4` deprecated `ErrorT` in favor of `ExceptT`.  Consequently, `statestack` does not build with `-Werror`: https://travis-ci.org/diagrams/statestack

Options include:
- do nothing, live with the travis failures
- release a version that depends on `transformers >= 0.4`, provide an `ExceptT` instance instead
- provide neither instance

Thoughts?  I'm leaning towards the first, and keeping this issue open as "documentation".

**Comment by RyanGlScott** [comment]
Alternatively, I think the most ideal solution would be to use CPP pragmas to import `ExceptT` if a user has `transformers` >= 0.4 installed, and import `ErrorT` otherwise. [This pull request](https://github.com/diagrams/statestack/pull/2) implements it.

**Comment by RyanGlScott** [comment]
Actually, an even better idea would be to use the `transformers-compat` library to export `ExceptT` and related functions for those using old versions of `transformers`. I'll make a new pull request using this instead.

**Comment by byorgey** [comment]
Looks like this got fixed via @RyanGlScott 's PR but this issue never got closed.  Feel free to reopen if I misunderstood and there's still something that should be done.
