### ISSUE TITLE
Please allow newer `base`

### ISSUE THREAD

**Issue by ezzieyguywuf** [diagrams/statestack#9]
I have successfully built this using `ghc-8.10.3` and `base-4.14.1.0`, and there don't seem to be any issues.

If you can make this change and either release a new revision to hackage or a new version, then this will allow us to better package this project in gentoo.

**Comment by byorgey** [comment]
Sorry for never responding to this!  I've just uploaded a version of `statestack` that supports up through GHC 9.6.
